### ISSUE TITLE
feat: add toggle option

### ISSUE THREAD

**Issue by lucobellic** [lucobellic/edgy-group.nvim#11]
### Idea

User defined open function or command might not support toggle.
Instead of letting the user updating the open function in edgy.nvim it could be interesting to add a toggle option (per groups) to close window already open.

### Scenarios:

- All windows for a group are open: Toggle will close all of them
- One window in open (in a group a several window): **TODO**
- Toggle groups at different position with opposite state with toggle / non-toggle: **TODO**

### To solve:

- [x] How to handle window that are open in non-corresponding group (after command call or filetype redirection)?
- [x] What is the best behavior to have when only one window is open in a group of multiple window?
  - Close the remaining ones, or open the missing ones?
- [x] How to handle several groups at different position with both closed and open group?

### TODO:

- [x] With toggle option, do not open already open window
- [x] Add documentation on usage of `open` from edgy.nvim to not use command that toggle the view when toggle option is enabled, otherwise this will lead to strange behavior.

### Notes:

Since the current behavior of edgy-group.nvim is to open after each call, it could be better to open the missing window if toggle option is enabled otherwise close the window.
But this solution might be unusable since some window wouldn't open in certain condition (or after a delay) such as outline.
Toggle option could also simply close the edgebar if at least one window from the group is open in the correct group but this is not compatible with pinned view.

### Selected Solution:

Close the group if the selected index is the same as the currently activated one and if at least one window of the group is open.
